# Generated by Django 5.2.16 on 2026-08-03 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('hashtag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='タグ名')),
            ],
            options={
                'verbose_name': 'ハッシュタグ',
                'verbose_name_plural': 'ハッシュタグ',
                'db_table': 'hashtags',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50, verbose_name='国')),
                ('region', models.CharField(max_length=50, verbose_name='地域')),
            ],
            options={
                'verbose_name': '訪問先',
                'verbose_name_plural': '訪問先',
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('day_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日付')),
                ('title', models.CharField(max_length=100, verbose_name='Dayタイトル')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('media', models.ImageField(blank=True, upload_to='day_media/', verbose_name='写真')),
                ('day_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='base.location', verbose_name='ロケーション')),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Day',
                'db_table': 'days',
                'ordering': ['day_order'],
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='場所名')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='URL')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('spot_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='base.day', verbose_name='Day')),
            ],
            options={
                'verbose_name': 'Spot',
                'verbose_name_plural': 'Spot',
                'db_table': 'spots',
                'ordering': ['spot_order'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('main_media', models.ImageField(blank=True, upload_to='trip_media/', verbose_name='代表写真')),
                ('start_date', models.DateField(verbose_name='旅行開始日')),
                ('end_date', models.DateField(verbose_name='旅行終了日')),
                ('total_cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='合計費用')),
                ('overview', models.TextField(blank=True, verbose_name='概要・感想')),
                ('status', models.CharField(choices=[('draft', '作成中'), ('planned', '出発待ち'), ('traveling', '旅中'), ('completed', '旅完了')], default='draft', max_length=20, verbose_name='ステータス')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開設定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='base.category', verbose_name='カテゴリ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trip',
                'db_table': 'trips',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='base.trip', verbose_name='Trip'),
        ),
        migrations.AddField(
            model_name='day',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='base.trip', verbose_name='Trip'),
        ),
        migrations.CreateModel(
            name='TripHashtag',
            fields=[
                ('trip_hashtag_id', models.AutoField(primary_key=True, serialize=False)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_hashtags', to='base.hashtag', verbose_name='ハッシュタグ')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_hashtags', to='base.trip', verbose_name='Trip')),
            ],
            options={
                'verbose_name': 'Tripハッシュタグ',
                'verbose_name_plural': 'Tripハッシュタグ',
                'db_table': 'trip_hashtags',
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('trip', 'country', 'region'), name='unique_trip_location'),
        ),
        migrations.AddConstraint(
            model_name='triphashtag',
            constraint=models.UniqueConstraint(fields=('trip', 'hashtag'), name='unique_trip_hashtag'),
        ),
    ]
