# Generated by Django 5.2.16 on 2026-08-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_hashtag_location_day_spot_trip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='location',
        ),
        migrations.AddField(
            model_name='day',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='days', to='base.location', verbose_name='ロケーション'),
        ),
    ]
