# Generated by Django 5.2.16 on 2026-08-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_day_location_day_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dayタイトル'),
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.UniqueConstraint(fields=('trip', 'date'), name='unique_trip_day_date'),
        ),
    ]
