# Generated by Django 5.2.16 on 2026-08-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_day_title_day_unique_trip_day_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ['time', 'spot_order'], 'verbose_name': 'Spot', 'verbose_name_plural': 'Spot'},
        ),
        migrations.AddField(
            model_name='spot',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='時間'),
        ),
    ]
