# Generated by Django 5.2.16 on 2026-08-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_spot_options_spot_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ['spot_order'], 'verbose_name': 'Spot', 'verbose_name_plural': 'Spot'},
        ),
    ]
