# Generated by Django 5.2.16 on 2026-08-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_spot_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='タグ名'),
        ),
    ]
