# Generated by Django 5.2.16 on 2026-08-09 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_hashtag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='actual_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='実際の合計費用'),
        ),
        migrations.AddField(
            model_name='day',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='1日の予算'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='実際の合計費用'),
        ),
        migrations.CreateModel(
            name='DayExpense',
            fields=[
                ('day_expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='何に使ったか')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='金額')),
                ('expense_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_expenses', to='base.day', verbose_name='Day')),
            ],
            options={
                'verbose_name': 'Day費用',
                'verbose_name_plural': 'Day費用',
                'db_table': 'day_expenses',
                'ordering': ['expense_order'],
            },
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('trip_expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='費用名')),
                ('planned_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='予定金額')),
                ('actual_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='実際支払額')),
                ('payment_status', models.CharField(choices=[('unpaid', '未払い'), ('partial', '一部支払い'), ('paid', '支払い済み')], default='unpaid', max_length=20, verbose_name='支払い状態')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('expense_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_expenses', to='base.trip', verbose_name='Trip')),
            ],
            options={
                'verbose_name': 'Trip共通費用',
                'verbose_name_plural': 'Trip共通費用',
                'db_table': 'trip_expenses',
                'ordering': ['expense_order'],
            },
        ),
    ]
