# Generated by Django 5.2.16 on 2026-08-09 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_day_actual_cost_day_budget_alter_trip_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='actual_cost',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='実際の合計費用'),
        ),
        migrations.AlterField(
            model_name='day',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='1日の予算'),
        ),
        migrations.AlterField(
            model_name='dayexpense',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='tripexpense',
            name='actual_amount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='実際支払額'),
        ),
        migrations.AlterField(
            model_name='tripexpense',
            name='planned_amount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='予定金額'),
        ),
    ]
