# Generated by Django 5.2.16 on 2026-08-11 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_day_actual_cost_alter_day_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripexpense',
            name='payment_status',
        ),
    ]
