# Generated by Django 5.2.16 on 2026-08-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_tripexpense_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='memo',
            field=models.TextField(blank=True, verbose_name='メモ'),
        ),
        migrations.AddField(
            model_name='trip',
            name='memo',
            field=models.TextField(blank=True, verbose_name='メモ'),
        ),
    ]
