# Generated by Django 5.2.16 on 2026-08-17 20:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_day_memo_trip_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayLocation',
            fields=[
                ('day_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='訪問順')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_locations', to='base.day', verbose_name='Day')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_locations', to='base.location', verbose_name='訪問先')),
            ],
            options={
                'verbose_name': 'Day訪問先',
                'verbose_name_plural': 'Day訪問先',
                'db_table': 'day_locations',
                'ordering': ['location_order'],
                'constraints': [models.UniqueConstraint(fields=('day', 'location'), name='unique_day_location'), models.UniqueConstraint(fields=('day', 'location_order'), name='unique_day_location_order')],
            },
        ),
    ]
