# Generated by Django 5.2.16 on 2026-08-17 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20260818_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='locations',
        ),
    ]
