# Generated by Django 5.2.16 on 2026-08-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_day_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='days', through='base.DayLocation', through_fields=('day', 'location'), to='base.location', verbose_name='ロケーション'),
        ),
    ]
