# Generated by Django 5.2.16 on 2026-08-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_day_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ['spot_order'], 'verbose_name': 'スケジュール', 'verbose_name_plural': 'スケジュール'},
        ),
        migrations.AddField(
            model_name='spot',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='終了時間'),
        ),
        migrations.AddField(
            model_name='spot',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='name',
            field=models.CharField(max_length=100, verbose_name='スケジュール名'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='旧時間'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='url',
            field=models.URLField(blank=True, max_length=255, verbose_name='旧参考URL'),
        ),
    ]
