# Generated by Django 5.2.16 on 2026-08-19 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_copy_spot_time_to_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayReferenceUrl',
            fields=[
                ('day_reference_url_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='参考URL名')),
                ('url', models.URLField(max_length=500, verbose_name='参考URL')),
                ('url_order', models.PositiveIntegerField(default=1, verbose_name='表示順')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_urls', to='base.day', verbose_name='Day')),
            ],
            options={
                'verbose_name': 'Day参考URL',
                'verbose_name_plural': 'Day参考URL',
                'db_table': 'day_reference_urls',
                'ordering': ['url_order'],
            },
        ),
        migrations.CreateModel(
            name='SpotReferenceUrl',
            fields=[
                ('spot_reference_url_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='参考URL名')),
                ('url', models.URLField(max_length=500, verbose_name='参考URL')),
                ('url_order', models.PositiveIntegerField(default=1, verbose_name='表示順')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_urls', to='base.spot', verbose_name='スケジュール')),
            ],
            options={
                'verbose_name': 'スケジュール参考URL',
                'verbose_name_plural': 'スケジュール参考URL',
                'db_table': 'spot_reference_urls',
                'ordering': ['url_order'],
            },
        ),
        migrations.CreateModel(
            name='TripExpenseReferenceUrl',
            fields=[
                ('trip_expense_reference_url_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='参考URL名')),
                ('url', models.URLField(max_length=500, verbose_name='参考URL')),
                ('url_order', models.PositiveIntegerField(default=1, verbose_name='表示順')),
                ('trip_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_urls', to='base.tripexpense', verbose_name='全体費用')),
            ],
            options={
                'verbose_name': '全体費用参考URL',
                'verbose_name_plural': '全体費用参考URL',
                'db_table': 'trip_expense_reference_urls',
                'ordering': ['url_order'],
            },
        ),
        migrations.CreateModel(
            name='TripReferenceUrl',
            fields=[
                ('trip_reference_url_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='参考URL名')),
                ('url', models.URLField(max_length=500, verbose_name='参考URL')),
                ('url_order', models.PositiveIntegerField(default=1, verbose_name='表示順')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_urls', to='base.trip', verbose_name='Trip')),
            ],
            options={
                'verbose_name': 'Trip参考URL',
                'verbose_name_plural': 'Trip参考URL',
                'db_table': 'trip_reference_urls',
                'ordering': ['url_order'],
            },
        ),
    ]
