# Generated by Django 5.2.16 on 2026-08-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_dayreferenceurl_spotreferenceurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='time',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='url',
        ),
    ]
