# Generated by Django 5.2.16 on 2026-08-29 05:48

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "base",
            "0020_remove_spot_time_remove_spot_url",
        ),
    ]

    operations = [

        # =====================================
        # Spot
        # → Schedule
        #
        # 既存データはそのままで
        # モデル名だけ変更する
        # =====================================

        migrations.RenameModel(
            old_name="Spot",
            new_name="Schedule",
        ),

        # =====================================
        # spot_id
        # → schedule_id
        # =====================================

        migrations.RenameField(
            model_name="schedule",
            old_name="spot_id",
            new_name="schedule_id",
        ),

        # =====================================
        # spot_order
        # → schedule_order
        # =====================================

        migrations.RenameField(
            model_name="schedule",
            old_name="spot_order",
            new_name="schedule_order",
        ),

        # =====================================
        # Day → Schedule の関連名
        #
        # day.spots
        # → day.schedules
        # =====================================

        migrations.AlterField(
            model_name="schedule",
            name="day",
            field=models.ForeignKey(
                on_delete=(
                    django.db.models.deletion.CASCADE
                ),
                related_name="schedules",
                to="base.day",
                verbose_name="Day",
            ),
        ),

        # =====================================
        # Schedule Meta
        # =====================================

        migrations.AlterModelOptions(
            name="schedule",
            options={
                "ordering": [
                    "schedule_order",
                ],
                "verbose_name": (
                    "スケジュール"
                ),
                "verbose_name_plural": (
                    "スケジュール"
                ),
            },
        ),

        # =====================================
        # DBテーブル
        #
        # spots
        # → schedules
        # =====================================

        migrations.AlterModelTable(
            name="schedule",
            table="schedules",
        ),

        # =====================================
        # SpotReferenceUrl
        # → ScheduleReferenceUrl
        # =====================================

        migrations.RenameModel(
            old_name="SpotReferenceUrl",
            new_name="ScheduleReferenceUrl",
        ),

        # =====================================
        # spot_reference_url_id
        # → schedule_reference_url_id
        # =====================================

        migrations.RenameField(
            model_name="schedulereferenceurl",
            old_name="spot_reference_url_id",
            new_name=(
                "schedule_reference_url_id"
            ),
        ),

        # =====================================
        # spot
        # → schedule
        #
        # DB上では
        # spot_id
        # → schedule_id
        # =====================================

        migrations.RenameField(
            model_name="schedulereferenceurl",
            old_name="spot",
            new_name="schedule",
        ),

        # =====================================
        # ScheduleReferenceUrl の関連
        # =====================================

        migrations.AlterField(
            model_name="schedulereferenceurl",
            name="schedule",
            field=models.ForeignKey(
                on_delete=(
                    django.db.models.deletion.CASCADE
                ),
                related_name="reference_urls",
                to="base.schedule",
                verbose_name="スケジュール",
            ),
        ),

        # =====================================
        # DBテーブル
        #
        # spot_reference_urls
        # → schedule_reference_urls
        # =====================================

        migrations.AlterModelTable(
            name="schedulereferenceurl",
            table=(
                "schedule_reference_urls"
            ),
        ),
    ]