# Generated by Django 5.2.16 on 2026-08-29 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_spot_to_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSave',
            fields=[
                ('trip_save_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='保存日時')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='base.trip', verbose_name='保存したTrip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_saves', to=settings.AUTH_USER_MODEL, verbose_name='保存したユーザー')),
            ],
            options={
                'verbose_name': 'Trip保存',
                'verbose_name_plural': 'Trip保存',
                'db_table': 'trip_saves',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'trip'), name='unique_user_trip_save')],
            },
        ),
    ]
