# Generated by Django 5.2.16 on 2026-08-30 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_tripsave'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='source_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reused_trips', to='base.trip', verbose_name='参考元Trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='source_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_trips', to=settings.AUTH_USER_MODEL, verbose_name='参考元ユーザー'),
        ),
    ]
