# Generated by Django 5.2.16 on 2026-08-31 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_trip_source_trip_trip_source_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='actual_amount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Day実際支払額'),
        ),
        migrations.AddField(
            model_name='day',
            name='planned_amount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Day予定金額'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='actual_amount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='実際支払額'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='planned_amount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='予定金額'),
        ),
        migrations.AlterField(
            model_name='day',
            name='actual_cost',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='自由費実績'),
        ),
        migrations.AlterField(
            model_name='day',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='自由費予算'),
        ),
    ]
