# Generated by Django 5.2.16 on 2026-09-05 03:03

from django.db import migrations


COUNTRY_NAME_TO_CODE = {
    "日本": "JP",
    "カザフスタン": "KZ",
    "キルギス": "KG",
    "韓国": "KR",
}


COUNTRY_CODE_TO_NAME = {
    "JP": "日本",
    "KZ": "カザフスタン",
    "KG": "キルギス",
    "KR": "韓国",
}


def convert_country_names_to_codes(
    apps,
    schema_editor,
):

    Location = apps.get_model(
        "base",
        "Location",
    )

    for country_name, country_code in (
        COUNTRY_NAME_TO_CODE.items()
    ):

        Location.objects.filter(
            country=country_name
        ).update(
            country=country_code
        )


def convert_country_codes_to_names(
    apps,
    schema_editor,
):

    Location = apps.get_model(
        "base",
        "Location",
    )

    for country_code, country_name in (
        COUNTRY_CODE_TO_NAME.items()
    ):

        Location.objects.filter(
            country=country_code
        ).update(
            country=country_name
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "base",
            "0024_day_actual_amount_day_planned_amount_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            convert_country_names_to_codes,
            convert_country_codes_to_names,
        ),
    ]