# Generated by Django 5.2.16 on 2026-09-05 03:08

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_convert_location_country_to_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='国'),
        ),
    ]
