# Generated by Django 5.2.16 on 2026-09-05 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_location_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('packing_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('bag_type', models.CharField(choices=[('large', '大きなバッグ'), ('small', '小さなバッグ'), ('other', 'その他')], default='large', max_length=20, verbose_name='バッグ区分')),
                ('name', models.CharField(max_length=100, verbose_name='持ち物名')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='個数')),
                ('is_packed', models.BooleanField(default=False, verbose_name='準備済み')),
                ('item_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='base.trip', verbose_name='Trip')),
            ],
            options={
                'verbose_name': '持ち物',
                'verbose_name_plural': '持ち物',
                'db_table': 'packing_items',
                'ordering': ['bag_type', 'item_order', 'packing_item_id'],
            },
        ),
    ]
